<a href="https://colab.research.google.com/github/abhishekshah5486/Numpy-Tutorials/blob/main/ArrayOperations2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np

In [90]:
arr1 = np.array([2,3,5,6,7])
arr2 = np.array([4,5,6,7,2])

In [91]:
arr1+arr2

array([ 6,  8, 11, 13,  9])

In [92]:
arr1*arr2

array([ 8, 15, 30, 42, 14])

In [93]:
arr1 == arr2

array([False, False, False, False, False])

In [94]:
mat1 = np.array([[2,4], [1,3]])
mat2 = np.array([[3,4],[7,6]])
print(mat1.ndim, mat2.ndim)

2 2


In [95]:
np.matmul(mat1, mat2)

array([[34, 32],
       [24, 22]])

In [96]:
mat3 = np.array([[2,3,4],[5,6,7]])
mat4 = np.array([[2,3],[4,5],[6,7]])

In [97]:
np.matmul(mat3,mat4)

array([[40, 49],
       [76, 94]])

In [98]:
np.dot(mat3, mat4)

array([[40, 49],
       [76, 94]])

In [99]:
mat3 @ mat4

array([[40, 49],
       [76, 94]])

In [100]:
nums = np.array([1,2,4,5,6,6,6,7])

In [101]:
nums.sum()

25

In [102]:
nums.max()

7

In [109]:
print(np.mean(nums))
print(np.sum(nums))
print(np.max(nums))
print(np.min(nums))
print(np.median(nums))

4.166666666666667
25
7
1
4.5
1.1
