<a href="https://colab.research.google.com/github/abhishekshah5486/Numpy-Tutorials/blob/main/ArrayFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np

In [71]:
arr = [1,3,6,4,5,7,8]
arr

[1, 3, 6, 4, 5, 7, 8]

In [72]:
arr[0:2]

[1, 3]

In [73]:
arr[-4:-1]

[4, 5, 7]

In [74]:
arr[-4:]

[4, 5, 7, 8]

In [75]:
arr[1:4:2]

[3, 4]

In [77]:
arr = np.array([1,2,3,4,7,3,8,4,2,8,5,6,9,12,54,6])
arr.size

16

In [79]:
nums = arr.reshape(4,4)
nums

array([[ 1,  2,  3,  4],
       [ 7,  3,  8,  4],
       [ 2,  8,  5,  6],
       [ 9, 12, 54,  6]])

In [80]:
nums[-1][-1]

6

In [81]:
nums[:3, 0:2]

array([[1, 2],
       [7, 3],
       [2, 8]])

In [82]:
nums[1:3, 1:]

array([[3, 8, 4],
       [8, 5, 6]])