<a href="https://colab.research.google.com/github/abhishekshah5486/Numpy-Tutorials/blob/main/ArrayOperations3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np

In [110]:
mat = np.arange(1,16).reshape(3,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [111]:
np.sum(mat)

120

In [112]:
np.sum(mat, axis = 1)

array([15, 40, 65])

In [113]:
np.sum(mat, axis = 0)

array([18, 21, 24, 27, 30])

In [114]:
np.max(mat, axis = 0)

array([11, 12, 13, 14, 15])

In [115]:
np.max(mat, axis = 1)

array([ 5, 10, 15])

In [116]:
np.mean(mat, axis = 1)

array([ 3.,  8., 13.])

In [121]:
nums = np.array([4,7,1,-4,7,9])
np.sort(nums)

array([-4,  1,  4,  7,  7,  9])

In [122]:
# nums.sort()
nums

array([ 4,  7,  1, -4,  7,  9])

In [123]:
mat.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [124]:
np.transpose(mat)

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])