<a href="https://colab.research.google.com/github/abhishekshah5486/Numpy-Tutorials/blob/main/ArrayOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import numpy as np

In [71]:
arr = [1,3,6,4,5,7,8]
arr

[1, 3, 6, 4, 5, 7, 8]

In [72]:
arr[0:2]

[1, 3]

In [73]:
arr[-4:-1]

[4, 5, 7]

In [74]:
arr[-4:]

[4, 5, 7, 8]

In [75]:
arr[1:4:2]

[3, 4]

In [77]:
arr = np.array([1,2,3,4,7,3,8,4,2,8,5,6,9,12,54,6])
arr.size

16

In [79]:
nums = arr.reshape(4,4)
nums

array([[ 1,  2,  3,  4],
       [ 7,  3,  8,  4],
       [ 2,  8,  5,  6],
       [ 9, 12, 54,  6]])

In [80]:
nums[-1][-1]

6

In [81]:
nums[:3, 0:2]

array([[1, 2],
       [7, 3],
       [2, 8]])

In [82]:
nums[1:3, 1:]

array([[3, 8, 4],
       [8, 5, 6]])

In [83]:
# FANCY INDEXING/ BOOLEAN INDEXING

In [84]:
nums = np.array([6,3,9,1,10,4,7,12])

In [85]:
mask = nums>5
mask

array([ True, False,  True, False,  True, False,  True,  True])

In [86]:
nums[mask]

array([ 6,  9, 10,  7, 12])

In [87]:
nums[nums%2 == 0]

array([ 6, 10,  4, 12])

In [88]:
nums[nums%2 == 1]

array([3, 9, 1, 7])

In [89]:
nums[(nums>5) & (nums%2==0)]

array([ 6, 10, 12])