<a href="https://colab.research.google.com/github/abhishekshah5486/Numpy-Tutorials/blob/main/NumpyMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [13]:
type(arr)

numpy.ndarray

In [14]:
arr.ndim # Dimension of array

1

In [17]:
arr.size

4

In [18]:
arr.shape

(4,)

In [23]:
# imp function to learn
arr_new = arr.reshape((1,4))
arr_new.shape

(1, 4)

In [25]:
arr_new
arr_new.ndim

2

In [26]:
arr_col = arr.reshape((4,1))
arr_col.shape

(4, 1)

In [27]:
arr_col

array([[1],
       [2],
       [3],
       [4]])

In [29]:
matrix = np.array([[1,2],[3,4],[5,6],[7,8]])
matrix.ndim
print(matrix)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [30]:
matrix_Transpose = matrix.reshape(2,4)
matrix_Transpose

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])