<a href="https://colab.research.google.com/github/abhishekshah5486/Numpy-Tutorials/blob/main/NumpyMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [34]:
arr = np.array([3,7,9,12,3,6])

In [35]:
arr + 10

array([13, 17, 19, 22, 13, 16])

In [36]:
arr ** 2

array([  9,  49,  81, 144,   9,  36])

In [37]:
arr_sq = arr*arr
print(arr_sq)

[  9  49  81 144   9  36]


In [38]:
arr1 = np.array([2.3, 4.5, 6.7, 9.0], dtype = int)
arr1

array([2, 4, 6, 9])

In [39]:
arr2 = np.arange(2,4)
arr2

array([2, 3])

In [40]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
# np.arrange(start, stop, step)
# By Default datatype is integer

np.arange(-2,7,1.5)

array([-2. , -0.5,  1. ,  2.5,  4. ,  5.5])

In [43]:
a = np.array([3,4.5,7,8.0,45,9])
a.astype(int) #Changing the datatype of an array

array([ 3,  4,  7,  8, 45,  9])

In [52]:
np.linspace(0,100,10).astype(int)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

In [58]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

In [55]:
np.zeros(6).reshape((6,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [57]:
np.zeros(6).reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [59]:
np.zeros(6).reshape(2,3,1)

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])